version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    env_file:
      - 'compose/env.grafana'
    user: "0"
    volumes:
      - ./compose/data-grafana/:/var/lib/grafana
      - ./compose/conf-grafana/:/etc/grafana/provisioning/

  prometheus:
    image: prom/prometheus:v2.5.0
    volumes:
      - ./compose/data-prometheus/:/etc/prometheus/
    depends_on:
      - konduit-demo
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  konduit-demo:
     image:  local/konduit-demo:v2
     ports:
       - "9008:9008"
